module.exports = {
    classes: [
        'adept',
        'alchemist',
        'arcane archer',
        'ardent',
        'artificer',
        'assassin',
        'blackguard',
        'bladesinger',
        'barbarian',
        'bard',
        'battlemage',
        'battlerager',
        'beastlord',
        'binder',
        'bounty hunter',
        'cavalier',
        'cleric',
        'delver',
        'divine born',
        'dragon knight',
        'dragon rider',
        'dragonslayer',
        'druid',
        'duelist',
        'fighter',
        'gladiator',
        'healer',
        'illusionist',
        'inquisitor',
        'knight',
        'lurk',
        'medic',
        'monk ',
        'mystic',
        'necromancer',
        'ninja',
        'oracle',
        'paladin',
        'psion',
        'psyblade',
        'psychic warrior',
        'ranger',
        'rogue',
        'scavenger',
        'scout',
        'shadowdancer',
        'shaman',
        'sorcerer',
        'soulknife',
        'spidermage',
        'spider rider',
        'summoner',
        'swashbuckler',
        'thief',
        'thug',
        'warlock',
        'warlord',
        'warmage',
        'warrior',
        'whisperer',
        'witchhunter',
        'wizard',
        'psyblade',
        'powerful Smaug',
        'terrible Sauron'
    ],

    actions: [
        'killed',
        'hit',
        'worships',
        'was ressurected by',
        'was followed by',
        'found',
        'pretends to be',
        'was forsaken by',
        'saved',
        'destroyed the realm of',
        'played a song with',
        'was awakened by',
        'shouted \"\FOR THE HORDE" with',
        'is a mortal enemy to',
        'found the body of',
        'summoned'

    ],

    locations: [
        'the enchanted forest',
        'the Mount Doom',
        'the Arena of Fate',
        'his home',
        'Heaven',
        'Hell',
        'the pub',
        'the cemetery',
        'the shelter',
        'the dragon\'s lair',
        'the hollow planet',
        'his disturbed mind',
        'the eternal battleground'
    ]
}